### ISSUE TITLE
Have the CNBi operator trigger the PackageList pipeline when a CR of that type is created

### ISSUE THREAD

**Issue by codificat** [thoth-station/meteor-operator#107]
One of the `CustomNBImage`'s `buildType`s is `PackageList` ([example](https://github.com/thoth-station/opendatahub-cnbi/blob/fa7254656b60b69e7751924cb988b1ddda99ad9e/README.md#example-1)).

The CNBi operator needs to trigger the right pipeline for this build type when a CR of that type is created.

## Acceptance criteria

- [ ] `PipelineRun`(s) for the correct `Pipeline`(s) are created when a CNBi CR with `buildType: PackageList` is created
- [ ] the CNBI CR status is correctly updated throughout the execution of the pipelines
- [ ] errors are being properly handled

## Additional information

The pipeline that implements the logic for that build type is being developed in https://github.com/thoth-station/helm-charts/issues/50

**Comment by VannTen** [comment]
Maybe we could handle the triggering a bit differently:

Have the operator trigger a buildType `agnostic pipeline, and handle different
buildtype with different steps depending on the Pipeline.

something like :
```yaml

tasks:
- name: get-build-type
  taskSpec:
      results:
      - name: build-type
        type: string
      steps:
      - image: openshift-client
        args: 
        - oc
        - get
        - cnbi
        - outout=jsonpath=.spec.buildType
        - $(params.cnbi)
        stdoutConfig: $(results.build-type.path)
- name: package-list-specific-task
  when:
    - input: $(task.get-build-type.results.build-type)
      operator: in
      values:
      - package-list
  taskRef: {}
  # not sure if runAfter is needed in that case, I think not
```
